# Generated by Django 3.2.3 on 2021-12-31 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_name', models.CharField(default='', max_length=200)),
                ('Admin_Password', models.CharField(default='', max_length=20)),
                ('Std_Type', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
