# Generated by Django 3.2.3 on 2021-12-31 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admins',
            old_name='Admin_Password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='admins',
            old_name='Admin_name',
            new_name='name',
        ),
    ]
