# Generated by Django 3.2.3 on 2022-01-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20211231_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stud_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stud_name', models.CharField(default='', max_length=300)),
                ('Stud_mail', models.CharField(default='', max_length=300)),
                ('Stud_course', models.CharField(default='', max_length=300)),
                ('Stud_number', models.CharField(default='', max_length=300)),
                ('Stud_paid', models.CharField(default='', max_length=1000)),
                ('Stud_balance', models.CharField(default='', max_length=1000)),
                ('Stud_address', models.CharField(default='', max_length=500)),
                ('Stud_image', models.ImageField(blank=True, null=True, upload_to='Stud_image')),
                ('Course_amount', models.CharField(default='', max_length=1000)),
                ('Join_date', models.DateField()),
                ('End_date', models.DateField()),
            ],
        ),
    ]
