# Generated by Django 3.2.3 on 2022-01-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_stud_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud_reg',
            name='Stud_IDD',
            field=models.CharField(default='', max_length=300),
        ),
    ]
