# Generated by Django 3.2.3 on 2022-01-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_auto_20220104_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud_reg',
            name='End_date',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='stud_reg',
            name='Join_date',
            field=models.CharField(default='', max_length=300),
        ),
    ]
